#!/bin/bash
#
# my-apps
#
# chkconfig: 23456 90 60
# description: Mina applikationer, node.js och webbservers.
#
export PATH=/var/local/node-v14.8.0-linux-x64/bin:$PATH



case "$1" in
 'start')
   echo "Start Noteservice REST-service"
   cd /var/local/noteservice
   node dist/noteserviceapp.js&

   cd /var/local/spelbolagservice
   node dist/app.js&

   echo "Start webbapps"
   cd /var/local/webapps
   node src/httpserver&
   ;;
 'stop')
   echo "Stopping my applications.";;
esac
