#!/bin/bash
#
# tomcat        
#
# chkconfig: 
# description: 	Start up the Tomcat servlet engine.

# Source function library.
echo Tomee
. /etc/init.d/functions


RETVAL=$?
CATALINA_HOME="/usr/local/tomee/apache-tomee-plus-1.5.0"

case "$1" in
 start)
        if [ -f $CATALINA_HOME/bin/startup.sh ];
          then
	    echo $"Starting Tomcat"
            $CATALINA_HOME/bin/startup-instance1.sh&
$CATALINA_HOME/bin/startup-instance2.sh&
        fi
	;;
 stop)
        if [ -f $CATALINA_HOME/bin/shutdown.sh ];
          then
	    echo $"Stopping Tomcat"
            $CATALINA_HOME/bin/shutdown.sh&
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop}"
	exit 1
	;;
esac

exit $RETVAL

